#!/bin/bash

# This file is used to generate a file named src/kernel.s which contains the
# entire kernel source code

echo -en "\nDisassembling DelphineOS kernel. Please wait..."

dd if=src/kernel/kernel of=src/temp bs=8192 skip=1 2> /dev/null
objdump --disassemble src/temp > src/kernel.s
rm -f src/temp

echo -e "   OK\n"

echo -e "Take a look at src/kernel.s   :-)\n"
