#!/bin/sh

test_return()
{
   if [ $? != 0 ]
   then
      echo 'Error during installation !!!'
      umount $1
      rm -r wxy
      echo ''
      exit
   fi
}

echo
echo DelphineOS installation for bochs ...
echo


# Compilation du noyau !!!

make

# creation de la diskette virtuelle

mkdir wxy
dd if=/dev/zero of=bochs/ext2.img bs=1024 count=1390
mke2fs bochs/ext2.img -F -q
mount bochs/ext2.img wxy -o loop
cp ./src/kernel/kernel wxy/kernel

# compilation de mkboot.c
if [ -e mkboot ]
then
 echo
else
 gcc mkboot.c -o mkboot
fi


# Voir mkbochs.c
./mkboot ./bochs/ext2.img  wxy/kernel


echo 'Unmounting device ...   '
umount wxy

echo -n 'Compiling boot sector file ...   '
   a ./src/boot/boot.S
   test_return
   echo 'OK'

# On copie le secteur de boot sur le périphérique spécifié
   
   cp ./src/boot/boot bochs/boot.img
   dd if=bochs/ext2.img of=bochs/delphine.img bs=512 skip=2
   cat bochs/delphine.img >> bochs/boot.img
   test_return

rm -rf mkboot bochs/delphine.img bochs/ext2.img
rm -r wxy
echo 'OK'
echo ''
